### ISSUE TITLE
Aufsetzen und Konfiguration eines lokalen Webservers für Testzwecke

### ISSUE THREAD

**Issue by Jstn2004** [Studienarbeit-HomeDroid/HomeDroid-App#6]
## Beschreibung
Einen lokalen Webserver auf der Testumgebung einrichten, um eine Webseite für die Entwicklung und das Testen bereitzustellen. Der Server soll so konfiguriert werden, dass er die Webseite lokal ohne externe Hosting-Anforderungen ausführt.

## Aufgaben
1. **Webserver installieren**:
   - Auswahl und Installation eines geeigneten Webservers (z.B. Apache, Nginx oder Node.js-basierter Server) auf der Testmaschine.
   - Sicherstellen, dass alle notwendigen Abhängigkeiten (z.B. PHP, Python, Node.js) installiert sind.

2. **Server konfigurieren**:
   - Basis-Konfiguration des Servers (Host, Port, Dokumentenstamm) einrichten.
   - Aktivieren der benötigten Module (z.B. PHP, HTTPS, URL-Rewriting falls erforderlich).

3. **Webseite bereitstellen**:
   - Platzieren der Website-Dateien im richtigen Verzeichnis.
   - Smarthome Webseite soll bereitgestellt werden.

4. **Dokumentation**:
   - Dokumentation der Installationsschritte und Serverkonfiguration.
   - Anleitung zum Starten, Stoppen und Beheben von Problemen des Servers beifügen.

## Erwartetes Ergebnis
- Die Webseite soll lokal auf dem Testserver zugänglich und korrekt für die lokale Entwicklung und das Testen konfiguriert sein.

**Comment by wwwLuis** [comment]
Code für Server wird in extra Repository verwaltet
